//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackMyKid.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_ERR_LOG
    {
        public int row_id { get; set; }
        public System.DateTime log_date { get; set; }
        public string log_thread { get; set; }
        public string log_level { get; set; }
        public string log_source { get; set; }
        public string log_message { get; set; }
        public string exception { get; set; }
    }
}
