//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackMyKid.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationMember
    {
        public int row_id { get; set; }
        public string MemberID { get; set; }
        public int Organization_ID { get; set; }
        public string userName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string designation { get; set; }
        public string Address { get; set; }
        public string AddressLandMark { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Coutry { get; set; }
        public int PinCode { get; set; }
        public string Email { get; set; }
        public int PrimaryContactNo { get; set; }
        public Nullable<int> AlternativeContactNo { get; set; }
        public string LastUpdatedBy { get; set; }
        public string IsActive { get; set; }
        public System.DateTime cr_datetime { get; set; }
        public System.DateTime updt_datetime { get; set; }
    }
}
