//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackMyKid.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public int row_id { get; set; }
        public int Organization_ID { get; set; }
        public string Organization_Name { get; set; }
        public string Organization_Type { get; set; }
        public string AddressStreet1 { get; set; }
        public string AddressStreet2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int PinCode { get; set; }
        public int PrimaryContactNumner { get; set; }
        public Nullable<int> SecondaryContactNo { get; set; }
        public string Email { get; set; }
        public string IsActive { get; set; }
        public System.DateTime Cr_datetime { get; set; }
        public System.DateTime updt_datetime { get; set; }
        public string LastUpdatedBy { get; set; }
    }
}
